// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-TtcaQf7DE6OOCbgmysa_6M6I9lvmwE',
    appId: '1:591947001404:web:25c6e787a9ae0567f61d39',
    messagingSenderId: '591947001404',
    projectId: 'citizenready-c9556',
    authDomain: 'citizenready-c9556.firebaseapp.com',
    storageBucket: 'citizenready-c9556.firebasestorage.app',
    measurementId: 'G-12C7GC497Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjAOi6ZOL8-Pu1R8wNwbstxq9VFoL_wM',
    appId: '1:591947001404:android:1adb8ba237ff387bf61d39',
    messagingSenderId: '591947001404',
    projectId: 'citizenready-c9556',
    storageBucket: 'citizenready-c9556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGATchmDnusi1Q2v6PnVlronNriV7m3qY',
    appId: '1:591947001404:ios:33bd6dcd1c4f9761f61d39',
    messagingSenderId: '591947001404',
    projectId: 'citizenready-c9556',
    storageBucket: 'citizenready-c9556.firebasestorage.app',
    iosBundleId: 'com.example.crisisManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGATchmDnusi1Q2v6PnVlronNriV7m3qY',
    appId: '1:591947001404:ios:33bd6dcd1c4f9761f61d39',
    messagingSenderId: '591947001404',
    projectId: 'citizenready-c9556',
    storageBucket: 'citizenready-c9556.firebasestorage.app',
    iosBundleId: 'com.example.crisisManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd-TtcaQf7DE6OOCbgmysa_6M6I9lvmwE',
    appId: '1:591947001404:web:8bf2c6e1da0a4a06f61d39',
    messagingSenderId: '591947001404',
    projectId: 'citizenready-c9556',
    authDomain: 'citizenready-c9556.firebaseapp.com',
    storageBucket: 'citizenready-c9556.firebasestorage.app',
    measurementId: 'G-MB05BLHMXF',
  );
}
